# Generated by Django 3.2.2 on 2021-06-13 03:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 17', regex='^$|^[0-9]{17}$')])),
                ('username', models.CharField(max_length=25)),
                ('CF_handle', models.CharField(blank=True, max_length=24, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be in 3~24', regex='^$|^.{3,24}$')])),
                ('ProblemName', models.CharField(max_length=100)),
                ('Difficulty', models.IntegerField(default=0)),
                ('Time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
