# Generated by Django 3.2.2 on 2021-06-13 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_alter_challenge_time'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='challenge',
            table='Challenge',
        ),
    ]
