# Generated by Django 3.2.2 on 2021-06-13 02:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='CF_handle',
            field=models.CharField(max_length=24, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be in 3~24', regex='^$|^.{3,24}$')]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='DP_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='DataStructure_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Graph_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Greedy_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Implementation_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Math_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='guild',
            field=models.CharField(max_length=17, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 17', regex='^$|^[0-9]{17}$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=25),
        ),
    ]
