# Generated by Django 3.2.2 on 2021-06-13 03:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210613_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='CF_handle',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be in 3~24', regex='^$|^.{3,24}$')]),
        ),
    ]
